#
# For more info about the settings, please refre to the github repository:
# https://github.com/canonical/gh-jira-sync-bot
#

settings:
  # Jira project key to create the issue in
  jira_project_key: "SOLENG"

  # Dictionary mapping GitHub issue status to Jira issue status
  status_mapping:
    opened: Untriaged
    closed: done

  # (Optional) Jira project components that should be attached to the created issue
  # Component names are case-sensitive
  components:
    - openstack-exporter

  # (Optional) (Default: None) Parent Epic key to link the issue to
  epic_key: SOLENG-46

  # (Optional) Dictionary mapping GitHub issue labels to Jira issue types.
  # If label on the issue is not in specified list, this issue will be created as a Bug
  label_mapping:
    enhancement: Story
