# Example configuration file for prometheus-openstack-exporter
# Copyright (C) 2016 Canonical, Ltd.
#

listen_port: <YAML_listen_port>
cache_refresh_interval: <YAML_cache_refresh_interval>  # In seconds
cache_file: /var/cache/prometheus-openstack-exporter/<YAML_cloud_name><YAML_region_name>
cloud: <YAML_cloud_name>
openstack_allocation_ratio_vcpu: <YAML_cpu_allocation_ratio>
openstack_allocation_ratio_ram: <YAML_ram_allocation_ratio>
openstack_allocation_ratio_disk: <YAML_disk_allocation_ratio>

# To export hypervisor_schedulable_instances metric set desired instance size
schedulable_instance_size:
    ram_mbs: <YAML_ram_mbs>
    vcpu: <YAML_vcpu>
    disk_gbs: <YAML_disk_gbs>

# There is no way to retrieve them using OpenStack APIs
# For clouds deployed without swift, remove this part
#swift_hosts:
#    - host1.example.com
#    - host2.example.com

