name: prometheus-openstack-exporter
base: core20
version: git
summary: Exposes high level OpenStack metrics to Prometheus.
description: |
  Exposes high level OpenStack metrics to Prometheus

confinement: strict
grade: stable
apps:
  prometheus-openstack-exporter:
    command: 'bin/prometheus-openstack-exporter.wrapper'
    plugs: [network-bind, network]
    daemon: simple
parts:
  prometheus-openstack-exporter:
    plugin: python
    source: .
    build-packages:
      - build-essential
      - liberasurecode-dev
      - libncursesw5
      - libtinfo5
      - libpython3-stdlib
      - libpython3.8-minimal
      - libpython3.8-stdlib
      - python3.8-minimal
      - python3-distutils
      - python3-minimal
      - python3-pkg-resources
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-wheel
      # for building lxml
      - libxml2-dev
      - libxslt1-dev
      # for building cffi
      - libffi-dev
      # for building cryptography
      - rustc
      - cargo
      - libssl-dev
      - pkg-config
    stage-packages:
      - libdb5.3
      - liberasurecode-dev
  example-config:
    plugin: dump
    source: .
    organize:
      prometheus-openstack-exporter.yaml: etc/prometheus/prometheus-openstack-exporter.yaml.example
    prime:
      - etc/prometheus/prometheus-openstack-exporter.yaml.example
  snap-wrappers:
    plugin: dump
    source: .
    organize:
      snap_cmd_wrapper: bin/prometheus-openstack-exporter.wrapper
    prime:
      - bin/prometheus-openstack-exporter.wrapper
