# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test suite

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]

jobs:
  lint-unittests-docs-build:
    name: Lint and Unit tests
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        python-version: [2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        apt install python-virtualenv
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run lint checkers
      run: make lint
    - name: Run unit tests
      run: make test-python
